[package]
name = "stress_methods"
version = "0.1.0"
authors = ["jon lipstate <jon@lipstate.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.25.3"
